version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 app:app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.celery worker --loglevel INFO --logfile=./logs/celery.log
    volumes:
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - web
      - redis

  dashboard:
    build: .
    command: celery --broker=redis://redis:6379 -A app.celery flower --port=5555
    ports:
      - 5557:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
    depends_on:
      - web
      - redis
      - worker

  redis:
    image: redis:6-alpine
    expose:
      - 6379

volumes:
  postgres_data: